# cluster_config.yml - cluster configuration
__default__:
    account: kirklandj-lab
    partition: serial
    time: 08:00:00
    cpus-per-task: 2
    mem: 16G
    output: results/logs/slurm-%x.%A.%a.log

fastqc_reads:
    cpus-per-task: 4
    mem: 32G
    cores: 4
    time: 01:00:00
    name: "{rule}.{wildcards.sample}"
    output: results/logs/{rule}.{wildcards.sample}.log
    error: results/logs/{rule}.{wildcards.sample}.err

multiqc_raw:
    cpus-per-task: 4
    mem: 16G
    time: 01:00:00
    name: "{rule}"
    output: results/logs/{rule}.log
    error: results/logs/{rule}.err

fastq_screen:
    cpus-per-task: 4
    mem: 32G
    time: 01:00:00
    cores: 4
    name: "{rule}.{wildcards.sample}"
    output: results/logs/{rule}.{wildcards.sample}.log
    error: results/logs/{rule}.{wildcards.sample}.err

align_with_bowtie2:
    cpus-per-task: 16
    mem: 64G
    cores: 16
    time: 06:00:00
    name: "{rule}.{wildcards.sample}"
    output: results/logs/{rule}.{wildcards.sample}.log
    error: results/logs/{rule}.{wildcards.sample}.err

sam_to_bam:
    cpus-per-task: 4
    mem: 32G
    cores: 4
    time: 02:00:00
    name: "{rule}.{wildcards.sample}"
    output: results/logs/{rule}.{wildcards.sample}.log
    error: results/logs/{rule}.{wildcards.sample}.err

sort_bam:
    cpus-per-task: 4
    mem: 32G
    cores: 4
    time: 02:00:00
    name: "{rule}.{wildcards.sample}"
    output: results/logs/{rule}.{wildcards.sample}.log
    error: results/logs/{rule}.{wildcards.sample}.err

make_bigwig_raw:
    cpus-per-task: 4
    mem: 32G
    cores: 4
    time: 03:00:00
    name: "{rule}.{wildcards.sample}"
    output: results/logs/{rule}.{wildcards.sample}.log
    error: results/logs/{rule}.{wildcards.sample}.err

calculate_total_reads:
    cpus-per-task: 2
    mem: 16G
    cores: 2
    time: 01:00:00
    name: "{rule}.{wildcards.sample}"
    output: results/logs/{rule}.{wildcards.sample}.log
    error: results/logs/{rule}.{wildcards.sample}.err

make_bigwig_scaled:
    cpus-per-task: 4
    mem: 32G
    cores: 4
    time: 03:00:00
    name: "{rule}.{wildcards.sample}"
    output: results/logs/{rule}.{wildcards.sample}.log
    error: results/logs/{rule}.{wildcards.sample}.err

macs2_peak_calling:
    cpus-per-task: 8
    mem: 64G
    cores: 8
    time: 04:00:00
    name: "{rule}.{wildcards.sample}"
    output: results/logs/{rule}.{wildcards.sample}.log
    error: results/logs/{rule}.{wildcards.sample}.err

generate_alignment_plots:
    cpus-per-task: 2
    mem: 16G
    time: 01:30:00
    name: "{rule}"
    output: results/logs/{rule}.log
    error: results/logs/{rule}.err

generate_fragmentLength_files:
    cpus-per-task: 2
    mem: 16G
    time: 01:30:00
    name: "{rule}.{wildcards.sample}"
    output: results/logs/{rule}.{wildcards.sample}.log
    error: results/logs/{rule}.{wildcards.sample}.err

generate_fragLen_plots:
    cpus-per-task: 2
    mem: 16G
    time: 01:30:00
    name: "{rule}"
    output: results/logs/{rule}.log
    error: results/logs/{rule}.err

process_fragment_length:
    cpus-per-task: 4
    mem: 32G
    time: 01:30:00
    name: "{rule}.{wildcards.sample}"
    output: results/logs/{rule}.{wildcards.sample}.log
    error: results/logs/{rule}.{wildcards.sample}.err

calculate_frip:
    cpus-per-task: 2
    mem: 16G
    time: 01:30:00
    name: "{rule}.{wildcards.sample}"
    output: results/logs/{rule}.{wildcards.sample}.log
    error: results/logs/{rule}.{wildcards.sample}.err

generate_correlation_plot:
    cpus-per-task: 2
    mem: 16G
    time: 01:30:00
    name: "{rule}"
    output: results/logs/{rule}.log
    error: results/logs/{rule}.err

generate_peak_summary_plots:
    cpus-per-task: 2
    mem: 16G
    time: 01:30:00
    name: "{rule}"
    output: results/logs/{rule}.log
    error: results/logs/{rule}.err
