# ------------------------------------------------------------
# Alignment
# ------------------------------------------------------------
# Bowtie2 genome index path
bowtie2_genome: "/hpc-prj/kirkland/shared/scripts/mm10_bowtie2_index/mm10"   # mm10 genome index file path = "/hpc-prj/kirkland/shared/scripts/mm10_bowtie2_index/mm10"
                                                                             # GRCh38 genome index file path = "/hpc-prj/kirkland/shared/scripts/hg38_bowtie2_index/hg38"

# ------------------------------------------------------------
# Raw FASTQs Quality Control
# ------------------------------------------------------------
# If true, run FastQC, MultiQC, and FastQ Screen.
# If false, skip these rules. Use for rerunning the workflow after raw FASTQ QC has already been completed.
use_fastq_qc: true

# ------------------------------------------------------------
# Duplicate capping
# ------------------------------------------------------------
use_duplicate_cap: true

# Maximum number of read-pair fragments allowed at the exact same fragment coordinate.
# Recommended sensitivity runs: 3, 5, 7, and off.
duplicate_cap_max: 5

# ------------------------------------------------------------
# Random downsampling
# ------------------------------------------------------------
use_downsampling: true

# Options:
#   "manual" = uses `downsample_target_fragments` as downsample target and lets samples <= target through without downsampling
#   "lowest_with_floor" = use the lowest post-duplicate-cap sample that is >= downsample_minimum_acceptable_fragments as the target. 
#                         Samples below the target are not changed. This prevents one very low-depth sample from forcing all other 
#                         samples down to that low depth.
#   "lowest" = use the lowest post-duplicate-cap sample as target
downsample_target_mode: "manual"

# Used only when downsample_target_mode: "manual"
downsample_target_fragments: 20000000

# Used only when downsample_target_mode: "lowest_with_floor"
downsample_minimum_acceptable_fragments: 20000000

# Set to "none" for non-reproducible random downsampling.
# For comparisons across duplicate-cap settings, keep this fixed.
#downsample_seed: "none"
downsample_seed: 12345

# ------------------------------------------------------------
# Peak Calling
# ------------------------------------------------------------
# MACS2 parameters for peak calling
genome_size: "mm"                                                            # For human genome - "hs" / for mouse genome - "mm"
macs2_qvalue: 0.05                                                           # q-value cutoff for significant peaks

# ------------------------------------------------------------
# BigWigs
# ------------------------------------------------------------
# bamCoverage parameters for BigWig generation
binSize: 50                                                                  # default bin = 50 
effective_genome_size: 2730871774                                            # mm10 genome size - 2730871774       
                                                                             # GRCh38 genome size - 2913022398

# ------------------------------------------------------------
# Module Versions
# ------------------------------------------------------------
# Modules (for loading software dependencies)
fastqc: "fastqc/0.12.1"
multiqc: "multiqc/1.21"
fastq_screen: "fastq-screen/0.15.2"
samtools: "samtools/1.18"
bowtie2: "bowtie2/2.5.0"
deeptools: "deeptools/3.4.3"
macs2: "macs2/2.2.7.1"
R: "R/4.4.1-mkl"
bioconductor: "bioconductor/3.19 gsl"
bedtools: "bedtools/2.30.0"
